# site settings
title: My Data World
subtitle: by Justin Grima
email: justintgrima@gmail.com
description: Welcome to my page where you can get to know who I am and what I can bring to the table for you! From this website, you can explore and discover my past projects demonstrating my skills and abilities in data science, gain insight into my relevant past work experiences, read reflection pieces on my data science experiences, view my educational and training history, and access my contact details and various social media accounts at the bottom of the page. For a quick and easy form of communication, please message me by filling out the form at the bottom of the page. Enjoy!
baseurl: # the subpath of your site, e.g. /blog
url: https://justingrima.github.io # the base hostname & protocol for your site
author: Justin Grima
street_address:
city: Brisbane
state: QLD
zip_code: 4000
country: Australia, EU and Canadian citizens with work authorization in Australia. Interested in opportunities in these locations and the United States. Willing to relocate with covered expenses.
phone: <p>+61 434 006 852</p> <p>+1 647 920 7213</p>

# homepage tiles
tiles-source: Justin Grima # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/JustinGrima
  GitLab:
  Google-Plus:
  Instagram: https://www.instagram.com/justintime4datascience/
  LinkedIn: https://www.linkedin.com/in/justin-grima-852297155/
  Twitter:
  Facebook: https://www.facebook.com/justin.grima.5
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
